### ISSUE TITLE
Can't export beatmaps on Linux

### ISSUE THREAD

**Issue by YSpoof** [kabiiQ/BeatmapExporter#12]
Error opening database: Provided schema version 36 does not equal last set version 32.
    The osu!lazer database structure has updated since the last BeatmapExporter update.
   
Versions:

    OSU: 2023-1130.0-lazer

    BeatMapExporter: 1.3.6

**Comment by kabiiQ** [comment]
I'm not sure if the Linux lazer is just behind for some reason, or why it would be on version 32 despite that being what looks like the latest release. Generally lazer should be the same for the same versions across platforms...

Regardless, since that's not the case here, BeatmapExporter 1.3.3 would be the version compatible with this database revision "32": https://github.com/kabiiQ/BeatmapExporter/releases/tag/v1.3.3

**Comment by YSpoof** [comment]
Worked like a charm, thanks a lot ;)
