### ISSUE TITLE
Export by start date/date cut?

### ISSUE THREAD

**Issue by ookiineko** [kabiiQ/BeatmapExporter#5]
I am using lazer client for grabbing new beatmaps, after that I may want to export the newly added beatmaps to stable.

This tool already does a good job when I want to export all beatmaps from lazer to stable,
but when I add some new beatmaps to the lazer database I may want to export only the new ones.

Is this supported currently?

**Comment by kabiiQ** [comment]
A filter for time added would be pretty straightforward to add. 

Do you think it would be more useful to input a specific time, or (as it sounds in your case) being able to specify "how much" time is better? Something like an "added since 2 hours ago" filter.

**Comment by ookiineko** [comment]
true

**Comment by ookiineko** [comment]
also sometimes i find it can be hard to type the whole collection name (it can be long and i can forget or make mistakes), or it just simply strangely doesn't work for collections with japanese characters in the name

i hope i can select them from a list using indexes

**Comment by kabiiQ** [comment]
I have some time where I can write both of these features today. I'm adding a way to identify collections by an index and the "since" filter. 

It looks like there will need to be a small schema update with the next lazer version, so I'll probably release an update with these features at the same time as long as it's probably soon rather than having 2 updates.

**Comment by kabiiQ** [comment]
https://github.com/kabiiQ/BeatmapExporter/releases/tag/v1.3.0

**Comment by kabiiQ** [comment]
https://github.com/kabiiQ/BeatmapExporter/releases/tag/v1.3.0
