### ISSUE TITLE
Collection export

### ISSUE THREAD

**Issue by udbnt** [kabiiQ/BeatmapExporter#6]
ability to export collections over to normal osu via collection.db change, just an idea ^^

**Comment by ookiineko** [comment]
is this the thing you wanted: https://github.com/ookiineko/CollectionDowngrader

**Comment by ookiineko** [comment]
this feature is really simple but this project is mainly about exporting beatmaps instead of collections i think

**Comment by ookiineko** [comment]
> even though its still overcomplicated, something that would simply add the collections from lazer to stable would be sick since using that would need collection manager again

i dont know why you want to directly adding new collections from lazer to stable bcs what i use most is constantly overwriting the stable collection database with the one exported from lazer

since my use case is to download beatmaps right in the lazer client and add them to collections while playing all those in the stable client

but the feature u want is possible to implement, since we can already go through the lazer collection data, and it should be easy to parse the stable collection database, just append the new collection and basically it should be it (but some error checkings may be needed as well), but it will require some TUI or GUI and unfortunately i am not familiar with C# so... try to add this feature yourself

again i think my tool is simple and not overcomplicated, bcs what it does is very simple: downgrade the collection data and nothing else, one should use collection manager since they already support this.

one example is: use CollectionDowngrader to downgrade your collection database from lazer to a collection.db, open this exact file using CollectionManager, delete all the collections you don't want to add to your stable client collection database (you can do multi selection with ctrl or shift keys like you do in other gui apps), finally click file->open->osu! collection, this will load all the collections from stable but doesn't clear the collections you previously loaded from the downgraded collection.db (and not deleted manually after that) and now you just have to double check the result and save the collections to osu stable location (file->save->osu! collection)
