### ISSUE TITLE
Beatmaps exported into zips cannot be imported back into osu!lazer

### ISSUE THREAD

**Issue by kamild1996** [kabiiQ/BeatmapExporter#8]
The exporting process seems to complete without errors, but when I'm trying to import the exported beatmaps back into osu!lazer, I'm getting the error message "Beatmap import failed!".
![image](https://github.com/kabiiQ/BeatmapExporter/assets/5320414/6fbcf059-f111-42dd-b742-4f102717cfd0)
This happens when I unzip the file and try to import the songs individually in osu!lazer. If I try to open the whole zip file in osu!lazer, I get the "unexpected error occured" message instead.
There seem to be no issue importing beatmaps that were not exported as a zip file.

**Comment by kabiiQ** [comment]
Thanks for the report.

 You're definitely right but at this moment I don't understand what the problem is. osu (both stable and lazer) seem to dislike the version produced when zipping (the .osz is produced in memory and then written to a .zip, which is where I think there is some format difference). I see very subtle differences in the format that I'm not immediately sure how to change (or which exactly is causing the problem). 

The .osz is not obviously corrupt, all the files are present inside and are complete and it can be opened with 7zip. Yet the lazer logs say `No beatmap files found in the beatmap archive`...

For now, just zip the files yourself I suppose if you need that functionality. I won't remove the feature immediately; I'll give it another shot at trying to find the problem sometime first, but that might be the way it goes.
